/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface WowButton {
    }
    interface WowText {
        "mood"?: 'edited' | 'forwarded' | '';
    }
}
declare global {
    interface HTMLWowButtonElement extends Components.WowButton, HTMLStencilElement {
    }
    var HTMLWowButtonElement: {
        prototype: HTMLWowButtonElement;
        new (): HTMLWowButtonElement;
    };
    interface HTMLWowTextElement extends Components.WowText, HTMLStencilElement {
    }
    var HTMLWowTextElement: {
        prototype: HTMLWowTextElement;
        new (): HTMLWowTextElement;
    };
    interface HTMLElementTagNameMap {
        "wow-button": HTMLWowButtonElement;
        "wow-text": HTMLWowTextElement;
    }
}
declare namespace LocalJSX {
    interface WowButton {
    }
    interface WowText {
        "mood"?: 'edited' | 'forwarded' | '';
    }
    interface IntrinsicElements {
        "wow-button": WowButton;
        "wow-text": WowText;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "wow-button": LocalJSX.WowButton & JSXBase.HTMLAttributes<HTMLWowButtonElement>;
            "wow-text": LocalJSX.WowText & JSXBase.HTMLAttributes<HTMLWowTextElement>;
        }
    }
}
